import json
import time
import os
import sys
from openai import OpenAI
from tqdm import tqdm
from dotenv import load_dotenv

from custom_logger import setup_logger

# ==========================================
# CONFIGURATION
# ==========================================
# Only change PART value
PART = "part1"

INPUT_FILE = f"/workspace/data/distillation_{PART}.jsonl"
BATCH_INPUT_FILE = f"/workspace/data/batch_payload_{PART}.jsonl"
OUTPUT_FILE = f"/workspace/data/llm_judge_results_{PART}.jsonl"
ERROR_OUTPUT_FILE = "/workspace/data/llm_judge_errors_{PART}.jsonl"

MODEL_NAME = "gpt-5.5"


# Load env variables and setup logging
load_dotenv()
logger = setup_logger("BatchEvaluation")

# Requires OpenAI API key
client = OpenAI()

# ==========================================
# OBJECTIVE JUDGE PROMPT
# ==========================================
JUDGE_SYSTEM_PROMPT = """
You are an objective Clinical Audit AI. 
Your task is to audit medical data extractions generated by a Teacher LLM to ensure they are high enough quality to be used as 'Ground Truth' for fine-tuning a smaller student model.

Review the [RAW TEXT] and the teacher model's [EXTRACTION].

Evaluate strictly on these 5 'Distillation-Ready' criteria:
1. Summary Relevance: Does the summary capture the core clinical picture accurately for training purposes?
2. Reasoning Quality: Is the 'clinical_reasoning' logically sound and does it provide a clear 'Chain-of-Thought' that a student model could learn from?
3. Relationship Validity: Are the subject-predicate-object triplets medically accurate and extracted strictly from the raw text?
4. Keyword Quality: Are the keywords high-value clinical entities (drugs, diagnoses, labs)?
5. Hallucination/Noise: Is the extraction free of any information not present in the raw text?

OUTPUT FORMAT:
Output ONLY a valid JSON object matching this schema:
{
    "summary_score": <int 1-10>,
    "reasoning_score": <int 1-10>,
    "relationships_score": <int 1-10>,
    "keywords_score": <int 1-10>,
    "hallucination_detected": <boolean>,
    "overall_score": <int 1-10>,
    "judge_justification": "<string briefly explaining why this record is or is not suitable for training data>"
}
"""


def prepare_batch_file():
    """
    Converts a standard JSONL file to OpenAI's strict Batch API format
    """
    logger.info(f"Formatting {INPUT_FILE} for Batch API...")

    with open(INPUT_FILE, "r", encoding="utf-8") as f_in, \
    open(BATCH_INPUT_FILE, "w", encoding="utf-8") as f_out:
        
        for i, line in enumerate(f_in):
            record = json.loads(line)
            record_id = str(record.get("id", f"record_{i}"))
            record_data = record.get("data", {})

            student_extraction = {
                "summary": record_data.get("summary", ""),
                "clinical_reasoning": record_data.get("clinical_reasoning", ""),
                "relationships": record_data.get("relationships", ""),
                "keywords": record_data.get("keywords", "")
            }

            user_content = f"""
            [RAW TEXT]\n{record.get("raw_medical_text", "")}\n\n[EXTRACTION]\n{json.dumps(student_extraction)}"""

            # OpenAI batch request schema
            batch_request = {
                "custom_id": record_id,
                "method": "POST",
                "url": "/v1/chat/completions",
                "body": {
                    "model": MODEL_NAME,
                    "temperature": 0.0,
                    "max_completion_tokens": 500,
                    "reasoning": {"effort": "medium"},
                    "response_format": {"type": "json_object"},
                    "messages": [
                        {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
                        {"role": "user", "content": user_content.strip()}
                    ]
                }
            }
            f_out.write(json.dumps(batch_request) + "\n")
    
    logger.info(f"batch file {BATCH_INPUT_FILE} created successfully")


def main():
    # Prepare data
    prepare_batch_file()

    # Upload file to OpenAI
    logger.info("uploading file to OpenAI for batch evaluation")
    with open(BATCH_INPUT_FILE, "rb") as file_stream:
        uploaded_file = client.files.create(
            file=file_stream,
            purpose="batch"
        )

    # Create batch job
    logger.info("starting batch job...")
    batch_job = client.batches.create(
        input_file_id=uploaded_file.id,
        endpoint="/v1/chat/completions",
        completion_window="24h"
    )
    logger.info(f"batch id: {batch_job.id}")

    # Monitor progress with tqdm
    pbar = None
    while True:
        status_response = client.batches.retrieve(batch_job.id)
        
        # Initialize tqdm once OpenAI calculates th total request count
        if status_response.request_counts and status_response.request_counts.total > 0:
            if pbar is None:
                pbar = tqdm(
                    total=status_response.request_counts.total,
                    desc="Evaluating Records..."
                )

            current_progress = (status_response.request_counts.completed + 
                                status_response.request_counts.failed)

            # Update progress bar based on completed + failed
            pbar.n = current_progress
            pbar.refresh()

        if status_response.status in ["completed", "failed", "expired", "cancelled"]:
            break

        # Poll OpenAI every 30 seconds
        time.sleep(30)

    if pbar:
        pbar.close()

    # Download the results
    if status_response.status == "completed":
        logger.info("\nbatch evaluation complete. downloading results...")

        # Pull successful records
        if status_response.output_file_id:
            result_content = client.files.content(status_response.output_file_id).text
            with open(OUTPUT_FILE, "w") as f:
                f.write(result_content)
            f.close()
            logger.info(f"successfully saved evaluations to {OUTPUT_FILE}")
            
        # Pull failed records
        if status_response.error_file_id:
            error_content = client.files.content(status_response.error_file_id).text
            with open(ERROR_OUTPUT_FILE, "w", encoding="utf-8") as f:
                f.write(error_content)
            f.close()
            logger.warning(f"NOTE: Some records failed. Saved error logs to {ERROR_OUTPUT_FILE}")

    else:
        logger.error(f"batch execution failed with status: {status_response.status}")
        if status_response.errors:
            logger.error(f"errors:\n{status_response.errors}")

if __name__ == "__main__":
    main()

                   